packages/ilib-lint/docs/ReleaseNotes.md
packages/ilib-lint/package.json
packages/ilib-lint/src/Project.js
pnpm-lock.yaml

- did not correctly detect whether or not the formatter defined its own formatOutput() method or just inherited it from its parent, causing it not to give any output at all
- this merges into the update-ilib-lint branch first and then that should get merged to main

Fix a bug where the formatter was not being used correctly

---

packages/ilib-loctool-mrkdwn/MrkdwnJsFile.js
packages/ilib-loctool-mrkdwn/README.md
packages/ilib-loctool-mrkdwn/package.json
packages/ilib-loctool-mrkdwn/test/MrkdwnJsFile.test.js

It was never tested and did not work as documented. This change makes it work properly.

Make the outputStyle setting work as documented

---

.circleci/config.yml
package.json

- Halved turborepo concurrency in CI runs
- Running only affected tests on the PR, kept running everything on the main branch
This is to fix red CI due to `node[5874]: pthread_create: Resource temporarily unavailable`

Fix pipeline failures due to executor resources exhausted

---

packages/loctool/lib/ResourceConvert.js
packages/loctool/test/ResourceConvert.test.js

Summary: Added support for converting string targets containing HTML tags to plural resources. This includes handling both simple and nested HTML tags within the strings, such as:
* `There is <b>string</b>.`
* `There is <span><b>string</b></span>.`

loctool: Add support for converting string target with tag nodes to plural

---

packages/ilib-lint/src/formatters/ConfigBasedFormatter.js
packages/ilib-lint/src/formatters/__tests__/ConfigBasedFormatter.test.js
pnpm-lock.yaml

* Update the `ConfigBasedFormatter` to replace all instances of `eX` tag combinations.
* Add tests to verify the correct replacement of `eX` tags in various scenarios.
* Fix an issue where unreplaced `<eX/>` tags appeared in the linter output, ensuring all tags are properly replaced with highlight markers.

ilib-lint: Fix unreplaced <eX/> tag component in linter output

---

.changeset/tough-apples-hug.md
packages/ilib-loctool-php-resource/LICENSE
packages/ilib-loctool-php-resource/PHPResourceFile.js
packages/ilib-loctool-php-resource/PHPResourceFileType.js
packages/ilib-loctool-php-resource/README.md
packages/ilib-loctool-php-resource/package.json
packages/ilib-loctool-php-resource/test/PHPResourceFile.test.js
packages/ilib-loctool-php-resource/test/PHPResourceFileType.test.js
pnpm-lock.yaml

- copied from ilib-loctool-javascript-resource and modified to work with php (hence the ES5 code)
- still needs a loctool sample to show it working correctly, but all unit tests pass and this code is reviewable

ilib-loctool-php-resource: Add php resource file plugin for the loctool

---

.changeset/beige-falcons-mate.md
packages/ilib-assemble/package.json
packages/ilib-data-utils/package.json
packages/ilib-lint-common/package.json
packages/ilib-lint-python-gnu/package.json
packages/ilib-lint-python/package.json
packages/ilib-lint-react/package.json
packages/ilib-lint/package.json
packages/ilib-tools-common/package.json
packages/tmxtool/package.json
scripts/check-package-exports.js

Fixed package.jsons in multiple monorepo packages to resolve some potential edge cases where various older setups might exhibit unexpected behaviour (like trouble loading them) due to missing or inconsistent `main`, `module` and `exports` entrypoint definitions
* issue was discovered in tests for https://github.com/iLib-js/ilib-mono/pull/31
```log
ilib-loctool-properties:test
cache miss, executing 104049eb1388b187
> ilib-loctool-properties@1.0.5 test /home/runner/work/ilib-mono/ilib-mono/packages/ilib-loctool-properties
> jest
FAIL test/PropertiesFile.test.js
● Test suite failed to run
Cannot find module 'ilib-tools-common' from '../ilib-po/lib/Parser.js'
Require stack:
/home/runner/work/ilib-mono/ilib-mono/packages/ilib-po/lib/Parser.js …
```

Fix incomplete package entrypoint definitions

---

.changeset/red-elephants-destroy.md
packages/ilib-es6/package.json
packages/ilib-es6/test/global.test.js
pnpm-lock.yaml

This updates the es6 bindings around ilib v14.21.0 which was recently published after our LG friends updated it to support the updated locale data in CLDR 46.

ilib-es6: Update to track the newly published ilib v14.21.0

---

.changeset/real-months-arrive.md
packages/loctool/lib/GenerateMode.js
packages/loctool/lib/IntermediateFileFactory.js
packages/loctool/lib/LocalRepository.js
packages/loctool/lib/Project.js
packages/loctool/test/IntermediateFile.test.js
packages/loctool/test/Project.test.js

- can now write out intermediate files with the .pot extension
- can read in translated files with the .pot extension
- cleaned up more unit test artifacts that shouldn't be there after running the tests

loctool: Support reading and writing .pot files

---

.changeset/honest-icons-brake.md
.changeset/rotten-pears-kick.md
packages/ilib-tools-common/package.json
packages/ilib-tools-common/src/Resource.js
packages/ilib-tools-common/src/ResourceArray.js
packages/ilib-tools-common/src/ResourceConvert.js
packages/ilib-tools-common/src/ResourcePlural.js
packages/ilib-tools-common/src/index.js
packages/ilib-tools-common/test/ResourceConvert.test.js
packages/ilib-tools-common/test/ResourcePlural.test.js
packages/loctool/lib/ResourceConvert.js
packages/loctool/lib/convertResources.js
packages/loctool/package.json
packages/loctool/test/ConvertResources.test.js
pnpm-lock.yaml

- moved out of the loctool and into the library so that our conversion tool can also call it.
- also will be available for the plugins should they need it
- updated loctool to call the library instead of using its own implementation directly. (ie. the loctool behaviour hasn't changed.)

Move plural conversions from loctool to ilib-tools-common

---

.changeset/weak-fireants-brake.md
packages/ilib-loctool-regex/LICENSE
packages/ilib-loctool-regex/README.md
packages/ilib-loctool-regex/RegexFile.js
packages/ilib-loctool-regex/RegexFileType.js
packages/ilib-loctool-regex/bin/testregex.js
packages/ilib-loctool-regex/package.json
packages/ilib-loctool-regex/test/RegexFile.test.js
packages/ilib-loctool-regex/test/RegexFileType.test.js
packages/ilib-loctool-regex/test/testfiles/js/t1.js
packages/ilib-loctool-regex/test/testfiles/project.json
packages/ilib-loctool-regex/test/testfiles/tmpl/topic_types.tmpl
pnpm-lock.yaml

- intended for file formats that are simple enough that they can be parsed with regular expressions
- settings in the project config file allow you to specify the regular expressions and how to handle the parts that they match
- outputs regular Resource instances
- cannot write any file format, so must be used with a resource file type

ilib-loctool-regex: Add new regex-based plugin

---

.changeset/tiny-hairs-love.md
packages/ilib-tools-common/src/DirectoryWalk.js
packages/loctool/lib/LocalRepository.js
packages/loctool/test/LocalRepository.test.js
packages/loctool/test/Project.test.js
packages/loctool/test/testfiles/xliffsdeep/de/project-german.xliff
packages/loctool/test/testfiles/xliffsdeep/es/419/strings.xliff
packages/loctool/test/testfiles/xliffsdeep/fr/project-french.xliff
packages/loctool/test/testfiles/xliffsdeep/nl/NL/strings.xliff

- quick fix
- added a unit tests for a deep xliff dir and verified that the bug was fixed
- updated ilib-tools-common to add missing jsdoc descriptions for some parameters. Does not need need a new version. This can go out with the next tools update.

loctool: Fix a bug where recursive search of xliff dirs did not work right

---

CONTRIBUTING.md
package.json

Added `run:*` scripts to easily start loctool and linter directly in monorepo also allowing them to automatically load all plugins from monorepo.
This way, we can easily test (and debug) changes made to both apps and plugins at the same time without the need to manually link them.

Add scripts to run apps with monorepo context

---

.changeset/rich-humans-wonder.md
packages/ilib-loctool-tap-i18n/YamlFile.js
packages/ilib-loctool-tap-i18n/test/YamlFile.test.js

Added _required plural categories_ for target plurals output by this plugin. If translation for those categories is not provided, they will always fall back to the translation for `other`.
Hardcoded required category `many` for Polish and Russian.

(ilib-loctool-tap-i18n) Always output plural category `many` for Polish and Russian targets

---

.changeset/lovely-peaches-obey.md
packages/loctool/lib/Project.js
packages/loctool/lib/convert.js

- we need a Project instance in order to do a convert
- when the project instance was created, it attempts to load translations from the xliffsDir. However, now that translation loading from the xliffsDir happens recursively, the new Project attempted to load every xliff file in the xliffsDir directory (default: ".") which was waaaaay too big
- now we pass in a flag to the project constructor that turns off loading of translations for a project that is only needed for convert.

Don't load translations from xliffsDir during a convert

---

packages/ilib-tools-common/Gruntfile.js
packages/ilib-tools-common/src/index.js

Found these problems while attempting to use the new escapers from the regex plugin:
- escapers weren't processed properly with babel so there were no transpiled js files for them
- they weren't included as part of the package
- escaperFactory wasn't exported from the index.js so you couldn't use it
Fortunately, the escapers changes in ilib-tools-common are not published yet, so we can just merge this and it will go out with the next publish.

Fix packaging of the new escaper classes

---

.changeset/lucky-lions-bathe.md
packages/ilib-loctool-regex/RegexFile.js
packages/ilib-loctool-regex/test/RegexFile.test.js

- if any regex matches but shows an empty source string, now we skip that string and continue matching in the rest of the file

ilib-loctool-regex: Fix a bug where parsing stops after empty source string

---

.changeset/mighty-foxes-breathe.md
git-hooks/pre-push
packages/ilib-loctool-regex/README.md
packages/ilib-loctool-regex/RegexFile.js
packages/ilib-loctool-regex/package.json
packages/ilib-loctool-regex/test/RegexFile.test.js
pnpm-lock.yaml

- add a new setting `escapeStyle` to each expression
- when strings are extracted for files that match that expression, the named escape style is applied as an unescaper

ilib-loctool-regex: Add escaping support

---

.changeset/brave-papayas-joke.md
packages/ilib-lint/package.json
packages/ilib-lint/src/FormatterManager.js
packages/ilib-lint/src/formatters/JsonFormatter.js
packages/ilib-lint/src/plugins/BuiltinPlugin.js
packages/ilib-lint/test/FormatterManager.test.js
packages/ilib-lint/test/formatters/JsonFormatter.test.js
pnpm-lock.yaml

- add a built-in JsonFormatter to format results in json form for the purposes of graphing the results across your localization batches. This leaves out a lot of the details such as the source string or description, as these are not needed for graphing.

Add a JsonFormatter built-in plugin

---

.changeset/little-ghosts-battle.md
packages/ilib-po/src/Parser.ts
packages/ilib-po/test/Parser.test.ts

Prevents
```
TypeError: Cannot read properties of undefined (reading 'categories')
18:14:27      at Parser.parse (ilib-po/lib/Parser.js:208:83)
```
for languages which don't have forms defined in `packages/ilib-po/src/pluralforms.ts`.

(ilib-po) Fix Parser plural forms fallback to English

---

.changeset/gold-radios-tan.md
.changeset/good-donuts-melt.md
packages/ilib-xliff/src/TranslationUnit.js
packages/ilib-xliff/src/Xliff.js
packages/ilib-xliff/src/XmlUtil.js
packages/ilib-xliff/test/testXliff12.js
packages/ilib-xliff/test/testXliff20.js
packages/loctool/lib/Xliff.js
packages/loctool/lib/XliffSelect.js
packages/loctool/loctool.js
packages/loctool/test/XliffSelect.test.js
packages/loctool/test/__snapshots__/XliffSelect.test.js.snap
packages/loctool/test/log4js.json
packages/loctool/test/testfiles/java/t1.java

- added support for extended attributes (ie. custom attributes) on the translation unit element in the xliff
- support for both xliff v1 and v2
- for reading AND writing xliff files
- added support for specifying the project name and extended attributes on the command line
- project name gets added to translation units during the select
- modified the select code to add in the extended attributes and project name to the units that are selected
- the select code also adds and extra extended attribute that gives the original file name where the translation unit was selected from
- added support for extended attributes to the ilib-xliff library as well

loctool and ilib-xliff: Fix loctool select and add extended attributes

---

.changeset/thick-elephant-ears.md
.changeset/thick-pianos-grab.md
packages/ilib-loctool-po/POFile.js
packages/ilib-loctool-po/pluralforms.json
packages/ilib-loctool-po/test/POFile.test.js
packages/ilib-po/src/Generator.ts
packages/ilib-po/src/Parser.ts
packages/ilib-po/src/pluralforms.ts
packages/ilib-po/test/Generator.test.ts
packages/ilib-po/test/Parser.test.ts
packages/loctool/test/ResourcePlural.test.js
pnpm-lock.yaml

This PR fixes the handling of plural categories for Polish in the intermediate PO file and PO file. 
Initially, we had the following **incorrect mapping in the PO file**:
```
msgstr[0] → one
msgstr[1] → few
msgstr[2] → other
```
This mapping was incorrect because, as per the CLDR documentation, `msgstr[2]` corresponds to the `many` category, not `other`. Due to this misinterpretation, we were incorrectly assigning Polish plural categories.
This was hidden by fallback behavior in ICU/react-intl, where a missing `many` would fall back to `other,` giving seemingly correct results even though `many` was never explicitly defined.
The misunderstanding was compounded by the fact that GNU gettext supports only three plural categories (`one`, `few`, `many`) and does not support `other`, while the …

[ilib-loctool-po] [ilib-po] Correct Polish plural category handling for PO files

---

.changeset/brave-bananas-relax.md
packages/loctool/loctool.js

currently `-t ` is duplicated.
- -t or --target  and  -t or --translations

loctool: Fix the duplicated the short form option

---

.changeset/sharp-dragons-tickle.md
.changeset/yellow-otters-crash.md
packages/ilib-lint-common/src/FileStats.js
packages/ilib-lint-common/test/FileStats.test.js
packages/ilib-lint/src/formatters/JsonFormatter.js
packages/ilib-lint/src/plugins/XliffParser.js
packages/ilib-lint/src/rules/ResourceCompleteness.js
packages/ilib-lint/src/rules/ResourceRule.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralCategories.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralParams.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralSyntax.js
packages/ilib-lint/src/rules/ResourceSourceICUUnexplainedParams.js
packages/ilib-lint/src/rules/SourceRegexpChecker.js
packages/ilib-lint/test/ResourceSourceICUPluralSyntax.test.js
packages/ilib-lint/test/XliffParser.test.js
packages/ilib-lint/test/formatters/JsonFormatter.test.js

- ilib-lint-common: Added support for counting the number of source words in the FileStats object
- modules is already used as number of resources in the XliffParser, so we don't need to change anything there
- ilib-lint: Added ability to count source words
- Added support from FileStats for source words
- Added support to most results to output the locale of the result so we can slice and dice by locale if necessary
- Added tests for XliffParser to make sure it is producing the right file stats
- Added support in the json formatter for source words and for target locales of results

ilib-lint, ilib-lint-common: Update json formatter output so we can do better stats

---

.changeset/two-boats-love.md
docs/upgrades/README.md
docs/upgrades/ilib-loctool-json/2.0.0.md
packages/ilib-loctool-json/JsonFileType.js
packages/ilib-loctool-json/README.md
packages/ilib-loctool-json/test/JsonFile.test.js

All relative paths provided in loctool's config are treated as relative to the project's root - schema resolution should behave the same way. Additionally, fixed (added?) support for absolute schema paths.

(ilib-loctool-json) Fix schema path resolution

---

.changeset/perfect-shirts-travel.md
packages/ilib-loctool-javascript-resource/JavaScriptResourceFile.js
packages/ilib-loctool-javascript-resource/test/JavaScriptResourceFile.test.js

- Add the ability to specify a header and footer in the output js file:
- Use the same replacements as in output paths
(See loctool utils.formatPath() for details.)
```json
{
"settings": {
"javascript": {
"header": "const strings_[language] = ",
"footer": "export default strings_[language];\n"
}
}
}
```

ilib-loctool-javascript-resource: Add the ability to specify header and footer for the output js file

---

.changeset/violet-fans-think.md
packages/ilib-lint/src/formatters/AnsiConsoleFormatter.js
packages/ilib-lint/src/formatters/ConfigBasedFormatter.js
packages/ilib-lint/test/formatters/AnsiConsoleFormatter.test.js
packages/ilib-lint/test/formatters/ConfigBasedFormatter.test.js

- update the Ansi Console formatter to include the locale if it is available in the result
- added a test for the ansi console formatter
- update the config-based formatter to format the locale into the template format and added tests
- this should have been done in that earlier PR I did, but somehow I updated all rules to include the locale and missed the part where you format it in the results!

ilib-lint: Make sure to output locale when formatting results

---

.changeset/calm-kids-compare.md
packages/loctool/README.md
packages/loctool/lib/GenerateMode.js
packages/loctool/lib/LocalRepository.js
packages/loctool/lib/Project.js
packages/loctool/loctool.js
packages/loctool/test/GenerateMode.test.js
packages/loctool/test/LocalRepository.test.js
packages/loctool/test/Project.test.js
packages/loctool/test/ProjectFactory.test.js

- the dir may now contain files that are not xliffs, so translationsDir is more descriptive
- xliffsDir is still supported for backwards compatibility

loctool: deprecate xliffsDir in favor of translationsDir

---

.changeset/shy-ads-tell.md
packages/loctool/lib/GenerateMode.js
packages/loctool/lib/LocalRepository.js
packages/loctool/lib/Project.js
packages/loctool/loctool.js
packages/loctool/test/Project.test.js
packages/loctool/test/ProjectFactory.test.js

- translationsDir setting had a default, which meant that it never looked at the xliffsDir setting.
- Now, if the xliffsDir setting is available, it will use that first, and then fall back to the translationsDir setting or its default.
- added some unit tests to verify that it is working properly
- tested in a real project to make sure it works as expected without modifying the existing project.json

loctool: Fix incorrect xliffsDir handling

---

packages/ilib-lint/test/rules/ResourceICUPluralTranslation.test.js

Extra unit test for functionality which we thought we don't have - but turns out we already do (since https://github.com/iLib-js/ilib-mono/pull/89).

(ilib-lint) ResourceICUPluralTranslation should not report missing translation for categories with no text

---

.changeset/lazy-pears-prove.md
packages/ilib-lint/src/plugins/BuiltinPlugin.js
packages/ilib-lint/src/rules/ResourceQuoteStyle.js
packages/ilib-lint/test/ResourceQuoteStyle.test.js
packages/ilib-lint/test/ResourceTargetChecker.test.js

- Implement fix for quote style rule
- only fixes quotes which exist in the target but are wrong. It cannot fix missing quotes because it doesn't know where to put them.
- quote chars can be separated from the text by a non-breaking space (French)
- can deal with Japanese properly too. ie. Only primary quotes, no secondary, but also [square brackets] are accepted as quotes.
- Added fix for a declarative rule resource-no-space-between-double-and-single-byte-character
- the extra spaces are removed
- Fix for rule resource-dnt-terms, which was supposed to be part of this batch, is not possible because we don't know which part of the target string was translated but shouldn't be

ilib-lint: Added auto-fix for two rules: quote style and no space between single-byte chars and double-byte punctuation

---

.changeset/dry-rice-type.md
.changeset/nervous-eyes-obey.md
packages/ilib-env/src/index.js
packages/ilib-env/test/env.test.js
packages/ilib-loader/package.json
packages/ilib-localedata/package.json

- if you set the platform to "mock" to test in a mock environment, ilib-env would get the top scope wrong under pnpm without the jsdom environment. To work around that, we first check for the existence of "window", then "global", then finally, "this" to guess at the actual right top scope properly under most platforms.

[ilib-env] Fix ilib-env to return the right top scope

---

packages/ilib-lint/docs/resource-anguilar-named-params.md
packages/ilib-lint/src/rules/ResourceCompleteness.js
packages/ilib-lint/src/rules/ResourceDNTTerms.js
packages/ilib-lint/src/rules/ResourceICUPluralTranslation.js
packages/ilib-lint/src/rules/ResourceICUPlurals.js
packages/ilib-lint/src/rules/ResourceNoTranslation.js
packages/ilib-lint/src/rules/ResourceSourceChecker.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralCategories.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralParams.js
packages/ilib-lint/src/rules/ResourceSourceICUPluralSyntax.js
packages/ilib-lint/src/rules/ResourceSourceICUUnexplainedParams.js
packages/ilib-lint/src/rules/ResourceXML.js
packages/ilib-lint/test/ResourceNoFullwidthDigits.test.js

Two tests for the `resource-no-fullwidth-digits` rule are failing because `DeclarativeResourceRule.checkString` is throwing errors due to missing arguments after calling `ResourceTargetChecker.matchString()` for plural and array resources.
For the plural resource, the error is:
```
Cannot create a ResourceStringLocator for a plural resource without a plural category.
```
For the array resource, the error is:
```
Cannot create a ResourceStringLocator for an array resource without an index.
```

[ilib-lint] Add tests for resource-no-fullwidth-digits rule

---

.changeset/curvy-crabs-ring.md
packages/ilib-lint/src/plugins/BuiltinPlugin.js
packages/ilib-lint/test/ResourceMatcher.test.js

- Fixed the regex for parsing URLs in the resource-url-match rule
- does not accept a dot as the last character in the string anymore
- now supports URL queries, hashes, and URL-encoded characters

Fix resource-url-match rule

---

packages/ilib-lint/test/ResourceQuoteStyle.test.js

- Single quotes in English that are used as apostrophes are handled correctly and do not trigger a test to for matching quotes in the target
- no source code is changed. Just added tests to verify it.

Added unit tests to show that single quotes are handled properly

---

.changeset/long-clocks-impress.md
packages/ilib-lint/src/rules/ResourceCamelCase.js
packages/ilib-lint/src/rules/ResourceKebabCase.js
packages/ilib-lint/src/rules/ResourceSnakeCase.js
packages/ilib-lint/test/rules/ResourceCamelCase.test.js
packages/ilib-lint/test/rules/ResourceKebabCase.test.js
packages/ilib-lint/test/rules/ResourceSnakeCase.test.js

- Fixed a bug where the exceptions for some rules were not taking effect
- resource-kebab-case, resource-camel-case, and resource-snake-case
- Syntax as noted in their documentation for exceptions did not work
- Problem was that the constructor of these rules was checking the wrong properties that RuleManager.get() was passing in

ilib-lint: Fix rule params from the linter config

---

.changeset/hungry-bugs-lie.md
.changeset/lemon-dots-sparkle.md
packages/ilib-lint-apple/package.json
packages/ilib-lint/src/formatters/AnsiConsoleFormatter.js

- fixed ansi console formatter to not throw exceptions if the Result object it is trying to format doesn't have all of the properties it is expecting to find.
- fix ilib-lint-apple package.json so that the linter can load it properly

Fix ilib-lint hang

---

.changeset/tall-peas-hope.md
packages/ilib-lint/docs/resource-kebab-case.md
packages/ilib-lint/src/rules/ResourceKebabCase.js
packages/ilib-lint/test/rules/ResourceKebabCase.test.js

- This avoids all the false positives with hyphenated words in English that only have a single dash in them.

ilib-lint: Modify kebab rule to require at least 2 dashes

---

.changeset/few-sheep-fly.md
packages/ilib-lint/docs/resource-icu-plurals-translated.md
packages/ilib-lint/src/rules/ResourceICUPluralTranslation.js
packages/ilib-lint/test/rules/ResourceICUPluralTranslation.test.js

- Added the ability to specify exceptions to the resource-icu-plural-translated rule so that it does not produce warnings for those exception words and phrases. Now you can list the exceptions by locale in the parameters to the rule:
```
"rulesets": {
"myruleset": {
"resource-icu-plural-translated": {
"exceptions": {
"it-IT": ["File", "Files"]
}
}
}
}
```

ilib-lint: Fix false positives

---

.changeset/lovely-horses-call.md
packages/ilib-lint/src/rules/ResourceSentenceEnding.js
packages/ilib-lint/test/rules/ResourceSentenceEnding.test.js

- Fix resource-sentence-ending rule to reduce false positives
- If the source ends in non-sentence-ending punctuation or no punctuation at all, then do not flag and remove the non-sentence-ending punctuation from the target, even if it is different
- Added support for Bengali sentence-ending punctuation
- A regular western period was incorrectly used instead of the Bengali period (danda) 
- Fix support for French sentence-ending punctuation
- In French, you put a non-breaking space between the last text and the sentence-ending punctuation
- This change will ensure that the non-breaking space is there.
- If there is a breaking space, it will be converted to a non-breaking space.
- If there is no space at all, a non-breaking space will be added.
- If there is already a non-breaking space, …

Fix punct at end

---

.changeset/old-moles-brake.md
.changeset/proud-rockets-whisper.md
packages/ilib-lint-common/src/Serializer.js
packages/ilib-lint/src/Project.js
packages/ilib-lint/src/plugins/LineSerializer.js
packages/ilib-lint/src/plugins/XliffSerializer.js
packages/ilib-lint/src/plugins/string/StringSerializer.js
packages/ilib-lint/test/XliffSerializer.test.js

... so that it doesn't crash when given bogus input. 
Given that I can't reproduce the problem from the lint report, all we can do is this defensive code.

Put defensive code into the serializers in ilib-lint

---

.changeset/sour-plants-flow.md
packages/ilib-lint/src/FileType.js
packages/ilib-lint/src/Project.js
packages/ilib-lint/src/index.js
packages/ilib-lint/test/FileType.test.js
packages/ilib-lint/test/Project.test.js

- now gets and uses the right locales
- command-line overrides the config file which overrides the default
- before, it only used the defaults!

Get and use the right locales in the linter

---

.changeset/mighty-lemons-visit.md
packages/ilib-lint/docs/resource-sentence-ending.md
packages/ilib-lint/src/rules/ResourceSentenceEnding.js
packages/ilib-lint/test/rules/ResourceSentenceEnding.test.js

- ResourceSentenceEnding rule enhancements to support various exception
- Added minimumLength configuration option (default: 10) to skip checking short strings/abbreviations
- Added automatic skipping of strings with no spaces
- Added exceptions array per locale to skip specific source strings from checking
- Enhanced punctuation detection for quoted content to handle punctuation after closing quotes
- Updated rule documentation with new configuration options and examples

Added support for exceptions in the resource sentence ending rule

---

.changeset/thick-kings-impress.md
packages/loctool/lib/LocalRepository.js
packages/loctool/test/LocalRepository.test.js

Changes
* Duplicate paths are removed to avoid redundant file system operations before reading translation files.
* This change ensures `translationsDir` contains only unique, absolute paths.
Cause
* The settings values for `loctool` can be provided either as arguments or defined in `project.json`.  
When passed as arguments, these `settings` are merged into `options.settings` by [ProjectFactory](https://github.com/iLib-js/ilib-mono/blob/main/packages/loctool/lib/ProjectFactory.js#L62).
Later, both `settings` and `options.settings` are merged again within the [Project](https://github.com/iLib-js/ilib-mono/blob/main/packages/loctool/lib/Project.js#L139).  
Since `JSUtils.merge` allows duplicate elements in arrays, this can result in `translationsDir` containing redundant paths.

loctool: Normalize and deduplicate translationsDir paths
